vim.cmd'command! -bar -bang Unlink packadd vim-eunuch <Bar> Unlink<bang>'
vim.cmd'command! -bar -bang Remove Unlink<bang>'
vim.cmd'command! -bar -bang Delete packadd vim-eunuch <Bar> Delete<bang>'
vim.cmd'command! -bar -nargs=1 -bang -complete=file Move packadd vim-eunuch <Bar> Move<bang> <args>'
vim.cmd'command! -bar -nargs=1 -bang -complete=file Rename packadd vim-eunuch <Bar> Rename<bang> <args>'
vim.cmd'command! -bar -bang -nargs=+ Chmod packadd vim-eunuch <Bar> Chmod<bang> <args>'
vim.cmd'command! -bar -bang -nargs=? -complete=dir Mkdir packadd vim-eunuch <Bar> Mkdir<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Cfind   packadd vim-eunuch <Bar> Cfind<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Clocate packadd vim-eunuch <Bar> Clocate<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Lfind   packadd vim-eunuch <Bar> Lfind<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Llocate packadd vim-eunuch <Bar> Llocate<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=? SudoEdit packadd vim-eunuch <Bar> SudoEdit<bang> <args>'
vim.cmd'command! -bar SudoWrite delcommand SudoWrite <Bar> packadd vim-eunuch <Bar> SudoEdit'
vim.cmd'command! -bar -nargs=? Wall packadd vim-eunuch <Bar> Wall <args>'
vim.cmd'command! -bar W Wall'
