vim.cmd'command! -bar -bang Unlink packadd vim-eunuch | Unlink<bang>'
vim.cmd'command! -bar -bang Remove Unlink<bang>'
vim.cmd'command! -bar -bang Delete packadd vim-eunuch | Delete<bang>'
vim.cmd'command! -bar -nargs=1 -bang -complete=file Move packadd vim-eunuch | Move<bang> <args>'
vim.cmd'command! -bar -nargs=1 -bang -complete=custom,s:Rename_complete Rename packadd vim-eunuch | Rename<bang> <args>'
vim.cmd'command! -bar -bang -nargs=+ Chmod packadd vim-eunuch | Chmod<bang> <args>'
vim.cmd'command! -bar -bang -nargs=? -complete=dir Mkdir packadd vim-eunuch | Mkdir<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Cfind   packadd vim-eunuch | Cfind<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Clocate packadd vim-eunuch | Clocate<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Lfind   packadd vim-eunuch | Lfind<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=+ Llocate packadd vim-eunuch | Llocate<bang> <args>'
vim.cmd'command! -bar -bang -complete=file -nargs=? SudoEdit packadd vim-eunuch | SudoEdit<bang> <args>'
vim.cmd'command! -bar -nargs=? Wall packadd vim-eunuch | Wall <args>'
