vim.cmd'command! Delete packadd vim-eunuch | Delete'
vim.cmd'command! -bang Unlink packadd vim-eunuch | Unlink<bang>'
vim.cmd'command! -bang Remove packadd vim-eunuch | Remove<bang>'
vim.cmd'command! -nargs=1 -complete=file -bang Move packadd vim-eunuch | Move <args>'
vim.cmd'command! -nargs=1 -complete=file -bang Rename packadd vim-eunuch | Rename <args>'
vim.cmd'command! -nargs=1 Chmod packadd vim-eunuch | Chmod <args>'
vim.cmd'command! -bang -nargs=1 -complete=dir Mkdir packadd vim-eunuch | Mkdir<bang> <args>'
vim.cmd'command! -nargs=+ -bang Cfind packadd vim-eunuch | Cfind<bang> <args>'
vim.cmd'command! -nargs=+ -bang Lfind packadd vim-eunuch | Lfind<bang> <args>'
vim.cmd'command! -nargs=+ -bang Clocate packadd vim-eunuch | Clocate <args>'
vim.cmd'command! -nargs=+ -bang Llocate packadd vim-eunuch | Llocate<bang> <args>'
vim.cmd'command! -nargs=1 -complete=file SudoEdit packadd vim-eunuch | SudoEdit'
vim.cmd'command! SudoWrite packadd vim-eunuch | SudoWrite'
vim.cmd'command! Wall packadd vim-eunuch | Wall'
vim.cmd'command! W packadd vim-eunuch | W'
